export const quizList = [
  {
    Q: "What does CPU stand for?",
    op1: "Central Processing Unit",
    op2: "Computer Personal Unit",
    op3: "Central Programming Unit",
    op4: "Control Processing Unit",
    ans: "Central Processing Unit",
    hint: "It's the brain of the computer.",
    img: null,
  },
  {
    Q: "Which language is primarily used for web development?",
    op1: "Python",
    op2: "JavaScript",
    op3: "C++",
    op4: "Java",
    ans: "JavaScript",
    hint: "It works closely with HTML and CSS.",
    img: null,
  },
  {
    Q: "Identify the following component shown in the image.",
    op1: "Hard Drive",
    op2: "RAM",
    op3: "Motherboard",
    op4: "CPU",
    ans: "Hard Drive",
    hint: "It is a storage component.",
    img: "https://m.media-amazon.com/images/I/81ca285MySL.jpg",
  },
  {
    Q: "What does RAM stand for?",
    op1: "Random Access Memory",
    op2: "Read And Modify",
    op3: "Read Access Module",
    op4: "Random Allocation Memory",
    ans: "Random Access Memory",
    hint: "It's a volatile memory.",
    img: null,
  },
  {
    Q: "Which of these is a programming language?",
    op1: "HTML",
    op2: "CSS",
    op3: "Python",
    op4: "SQL",
    ans: "Python",
    hint: "It’s often used in data science and AI.",
    img: null,
  },
  {
    Q: "What does URL stand for?",
    op1: "Uniform Resource Locator",
    op2: "Unified Resource Link",
    op3: "Uniform Reference Locator",
    op4: "Universal Reference Link",
    ans: "Uniform Resource Locator",
    hint: "It’s related to web addresses.",
    img: null,
  },
  {
    Q: "Identify the company logo shown in the image.",
    op1: "Apple",
    op2: "Microsoft",
    op3: "Google",
    op4: "IBM",
    ans: "Microsoft",
    hint: "The founder is Bill Gates.",
    img: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
  },
  {
    Q: "Which device is used to input data?",
    op1: "Monitor",
    op2: "Keyboard",
    op3: "Speaker",
    op4: "Printer",
    ans: "Keyboard",
    hint: "It has keys for typing.",
    img: null,
  },
  {
    Q: "Which symbol is used for comments in JavaScript?",
    op1: "//",
    op2: "#",
    op3: "/* */",
    op4: "<!-- -->",
    ans: "//",
    hint: "no hints available",
  },
  {
    Q: "What does HTML stand for?",
    op1: "HyperText Markup Language",
    op2: "HighText Machine Language",
    op3: "HyperTool Multi Language",
    op4: "HyperText Machine Language",
    ans: "HyperText Markup Language",
    hint: "no hints available",
    img: null,
  },
  {
    Q: "What does IDE stand for?",
    op1: "Integrated Development Environment",
    op2: "Internal Design Editor",
    op3: "Integrated Debugging Environment",
    op4: "Integrated Data Environment",
    ans: "Integrated Development Environment",
    hint: "used for coding",
    img: null,
  },

  {
    Q: "Which of these is an example of a database?",
    op1: "MySQL",
    op2: "React",
    op3: "Node.js",
    op4: "CSS",
    ans: "MySQL",
    hint: "no hints available",
    img: null,
  },
  {
    Q: "Which of these is not a programming language?",
    op1: "Java",
    op2: "Python",
    op3: "HTML",
    op4: "C++",
    ans: "HTML",
    hint: "It’s used for web page structure.",
    img: null,
  },
  {
    Q: "What does DNS stand for?",
    op1: "Domain Name System",
    op2: "Data Network Service",
    op3: "Domain Network Service",
    op4: "Digital Name System",
    ans: "Domain Name System",
    hint: "It’s a system.",
    img: null,
  },
  {
    Q: "Which type of network is used within a single building?",
    op1: "LAN",
    op2: "WAN",
    op3: "MAN",
    op4: "PAN",
    ans: "LAN",
    hint: "no hints available",
    img: null,
  },
  {
    Q: "Identify the operating system logo in the image.",
    op1: "Windows",
    op2: "Linux",
    op3: "MacOS",
    op4: "iOS",
    ans: "Linux",
    hint: "no hints available",
    img: "https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png",
  },
  {
    Q: "Which HTML tag is used to display an image?",
    op1: "<img>",
    op2: "<image>",
    op3: "<src>",
    op4: "<picture>",
    ans: "<img>",
    hint: "no hints available",
    img: null,
  },
  {
    Q: "What does AI stand for?",
    op1: "Artificial Intelligence",
    op2: "Automated Integration",
    op3: "Artificial Interaction",
    op4: "Automated Intelligence",
    ans: "Artificial Intelligence",
    hint: "no hints available",
    img: null,
  },
  {
    Q: "What does GPU stand for?",
    op1: "Graphics Processing Unit",
    op2: "General Processing Unit",
    op3: "Graphical Programming Unit",
    op4: "General Purpose Unit",
    ans: "Graphics Processing Unit",
    hint: "It’s responsible for rendering graphics.",
    img: null,
  },
  {
    Q: "What does SQL stand for?",
    op1: "Structured Query Language",
    op2: "Simple Query Language",
    op3: "Sequential Query Language",
    op4: "Secure Query Language",
    ans: "Structured Query Language",
    hint: "It's used for database management.",
    img: null,
  },

  {
    Q: "Identify this programming language logo:",
    op1: "Python",
    op2: "JavaScript",
    op3: "Java",
    op4: "C++",
    ans: "Python",
    hint: "its a scripting language",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png",
  },

  {
    Q: "What is the correct syntax to include JavaScript in HTML?",
    op1: "<script>",
    op2: "<js>",
    op3: "<javascript>",
    op4: "<code>",
    ans: "<script>",
    hint: "no hints available",
    img: null,
  },
];
